module.exports = {
  ROUTES: [{
    path: '/',
    component: require('../../pages/Index/Index.js').default,
    exact: true
  }, {
    path: '/signup',
    component: require('../../pages/Signup/Signup.js').default,
    exact: true
  }, {
    path: '/login',
    component: require('../../pages/Login/Login.js').default,
    exact: true
  }, {
    path: '/myevents',
    component: require('../../pages/Dashboard/Dashboard.js').default,
    exact: true,
    auth: true
  }, {
    path: '/myevents/invites',
    component: require('../../pages/Invites/Invites.js').default,
    exact: true,
    auth: true
  }, {
    path: '/myevents/create',
    component: require('../../pages/CreateEvent/CreateEvent.js').default,
    exact: true,
    auth: true
  }, {
    path: '/event/:event_id',
    component: require('../../pages/Event/Event.js').default,
    exact: true
  }, {
    path: '/myaccount',
    component: require('../../pages/MyAccount/MyAccount.js').default,
    exact: true,
    auth: true
  }, {
    path: '/store',
    component: require('../../pages/Store/Store.js').default,
    exact: true
  }, {
    path: '/cart',
    component: require('../../pages/Cart/Cart.js').default,
    auth: true
  }, {
    path: '/store/item/:item_id',
    component: require('../../pages/Item/Item.js').default,
    exact: true
  }, {
    path: '/payment',
    component: require('../../pages/Payment/Payment.js').default,
    exact: true,
    auth: true
  }, {
    component: require('../../pages/Page404/Page404.js').default
  }]
}